name: ASN Lookup

on:
  workflow_dispatch:
    inputs:
      asn:
        description: 'Autonomous System Number'
        required: true
        default: '215540'

jobs:
  lookup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run ASN to IP block script
        run: |
          python scripts/asn_to_ip_blocks.py ${{ github.event.inputs.asn }}

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: asn-${{ github.event.inputs.asn }}-blocks
          path: asn_${{ github.event.inputs.asn }}_blocks.txt
