name: ASN Lookup and Update File

on:
  workflow_dispatch:
    inputs:
      asn:
        description: 'Autonomous System Number'
        required: true
        default: '215540'

jobs:
  lookup_and_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run ASN lookup and update script
        run: |
          python scripts/asn_to_ip_blocks.py ${{ github.event.inputs.asn }}

      - name: Commit and push updated asn_block1.1.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add asn_block1.1.txt
          git commit -m "Update asn_block1.1.txt with new ASN ${{ github.event.inputs.asn }} blocks" || echo "No changes to commit"
          git push
